### ISSUE TITLE
No extention or Don't know what programm is it.

### ISSUE THREAD

**Issue by pk4tech** [SunnySkye/Dell-Bios-Password#1]
![image](https://user-images.githubusercontent.com/35728885/190962246-dc7d6d93-7800-4176-ae38-7e12f8260aa8.png)

![image](https://user-images.githubusercontent.com/35728885/190962301-fa79627c-3c30-45d8-af5a-9317a06ac2c4.png)
& in both .vbs and .bat or .c nothing gives every programm is error or i Might be no use in programming I only know is java

**Comment by SunnySkye** [comment]
it is a PowerShell script :)
The extension for the file should be .ps1
